apiVersion: apps/v1
kind: Deployment
metadata:
    name: keycloak
    labels:
        app: keycloak
        version: v1
        service: keycloak
spec:
    replicas: 1
    selector:
        matchLabels:
            app: keycloak
            version: v1
            service: keycloak
    template:
        metadata:
            labels:
                app: keycloak
                version: v1
                service: keycloak
                sidecar.istio.io/inject: "true"
        spec:
            containers:
                - name: keycloak
                  image: quay.io/keycloak/keycloak:25.0.2
                  args: ["start-dev"]
                  env:
                      - name: KEYCLOAK_ADMIN
                        value: "admin"
                      - name: KEYCLOAK_ADMIN_PASSWORD
                        value: "admin"
                      - name: KC_PROXY
                        value: "edge"
                  ports:
                      - name: http
                        containerPort: 8080
                  readinessProbe:
                      httpGet:
                          path: /realms/master
                          port: 8080