apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
    name: google
spec:
    hosts:
        - "accounts.google.com"
        - "oauth2.googleapis.com"
    location: MESH_EXTERNAL
    ports:
        - number: 443
          name: https
          protocol: TLS
    resolution: DNS
