apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
    name: stripe
spec:
    hosts:
        - api.stripe.com
    location: MESH_EXTERNAL
    ports:
        - number: 443
          name: https
          protocol: TLS
    resolution: DNS
