---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istio-egress-gateway
    namespace: flux-system
spec:
    releaseName: egress-gateway
    targetNamespace: istio-system
    interval: 1m
    timeout: 10m
    dependsOn:
        - name: istiod
          namespace: flux-system
    chart:
        spec:
            chart: gateway
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: flux-system
    values:
        service:
            type: ClusterIP
        autoscaling:
            enabled: true
        resources:
            limits:
                cpu: 100m
                memory: 256Mi
    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        # disableWait: true
        crds: Create
        createNamespace: true
