# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istiod
    namespace: flux-system
spec:
    releaseName: istiod
    targetNamespace: istio-system
    interval: 1m
    timeout: 10m
    dependsOn:
        - name: istio-base
          namespace: flux-system
    chart:
        spec:
            chart: istiod
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: flux-system
    values:
        defaults:
            meshConfig:
                enableTracing: true
                accessLogFile: /dev/stdout
                defaultConfig:
                    tracing: {}
                enablePrometheusMerge: true
                extensionProviders:
                    -   name: otel-tracing
                        opentelemetry:
                            port: 4317
                            service: opentelemetry-collector.observability.svc.cluster.local
                            resource_detectors:
                                environment: {}
            global:
                omitSidecarInjectorConfigMap: false
                proxy:
                    privileged: true
                    logLevel: info
                    resources:
                        limits:
                            cpu: 250m
                            memory: 512Mi
                    tracer: "zipkin"

    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        # disableWait: true
        crds: Create
        createNamespace: true
