---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: metrics-server
    namespace: flux-system
spec:
    releaseName: metrics-server
    targetNamespace: kube-system
    interval: 1m
    chart:
        metadata:
            labels:
                app.kubernetes.io/name: metrics-server
        spec:
            chart: metrics-server
            version: 3.12.1
            sourceRef:
                kind: HelmRepository
                name: metrics-server
                namespace: flux-system
    values:
        defaultArgs: []
        args:
            - "--kubelet-insecure-tls"
            - "--kubelet-preferred-address-types=InternalIP,ExternalIP"
    install:
        crds: Create
        createNamespace: true
