apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development
resources:
    - namespace.yaml
    - gateway.yaml
    - api-gateway.yaml
    - default-limits.yaml
    - peer-authentication.yaml
