# How to manage values files. Ref: https://fluxcd.io/docs/guides/helmreleases/#refer-to-values-inside-the-chart
# How to inject values: https://fluxcd.io/docs/guides/helmreleases/#cloud-storage
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cert-manager
    namespace: flux-system
spec:
    releaseName: cert-manager
    targetNamespace: cert-manager
    interval: 1m
    chart:
        spec:
            chart: cert-manager
            version: 1.15.0
            sourceRef:
                kind: HelmRepository
                name: cert-manager
                namespace: flux-system
    values:
        crds:
            enabled: true
        resources:
            request:
                cpu: 10m
                memory: 64Mi
            limits:
                cpu: 25m
                memory: 128Mi
    # Ref: https://fluxcd.io/docs/components/helm/api/#helm.toolkit.fluxcd.io/v2beta1.Install
    install:
        crds: Create
        createNamespace: true
