---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: external-secrets-resources
    namespace: flux-system
spec:
    interval: 1m
    path: ./infrastructure/external-secrets
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
