---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: environments
    namespace: flux-system
spec:
    interval: 1m
    path: ./clusters/local/environments
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
