---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: ingress
    namespace: flux-system
spec:
    interval: 1m
    path: ./clusters/local/ingress
    prune: true
    dependsOn:
        -   name: workloads
            namespace: flux-system
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
