---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: workloads
    namespace: flux-system
spec:
    interval: 1m
    path: ./clusters/local/workloads
    prune: true
    dependsOn:
        -   name: istio
            namespace: flux-system
    sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
